export const FakeRatings = [
  {
    name: 'Camille Sanchez',
    email: 'kasisyt@mailinator.com',
    rating: '1',
    comment: 'Explicabo Do repreh',
    date: '18/5/2020',
  },
  {
    name: 'Merrill Pitts',
    email: 'furu@mailinator.com',
    rating: '2',
    comment: 'Nemo ex aut aliquip ',
    date: '18/5/2020',
  },
  {
    name: 'Darrel Chaney',
    email: 'sirofutif@mailinator.com',
    rating: '4',
    comment: 'Mollit illo expedita',
    date: '19/5/2020',
  },
  {
    name: 'Harlan Solomon',
    email: 'fuciny@mailinator.com',
    rating: '5',
    comment: 'Veritatis a quis ull',
    date: '19/5/2020',
  },
  {
    name: 'Ria Griffith',
    email: 'nucyli@mailinator.com',
    rating: '4',
    comment: 'Eius obcaecati et pa',
    date: '19/5/2020',
  },
  {
    name: 'Mari Ray',
    email: 'famato@mailinator.com',
    rating: '3',
    comment: 'Aliquam nihil delect',
    date: '19/5/2020',
  },
  {
    name: 'Darrel Chaney',
    email: 'sirofutif@mailinator.com',
    rating: '4',
    comment: 'Mollit illo expedita',
    date: '20/5/2020',
  },
  {
    name: 'Harlan Solomon',
    email: 'fuciny@mailinator.com',
    rating: '5',
    comment: 'Veritatis a quis ull',
    date: '20/5/2020',
  },
  {
    name: 'Ria Griffith',
    email: 'nucyli@mailinator.com',
    rating: '4',
    comment: 'Eius obcaecati et pa',
    date: '20/5/2020',
  },
  {
    name: 'Mari Ray',
    email: 'famato@mailinator.com',
    rating: '3',
    comment: 'Aliquam nihil delect',
    date: '21/5/2020',
  },
  {
    name: 'Raphael Waller',
    email: 'nucu@mailinator.com',
    rating: '5',
    comment: 'Aliquid quisquam nul',
    date: '21/5/2020',
  },
  {
    name: 'Raphael Waller',
    email: 'nucu@mailinator.com',
    rating: '5',
    comment: 'Aliquid quisquam nul',
    date: '21/5/2020',
  },
]
